import { Outlet } from 'react-router-dom';
import Header from './components/Header';

function App() {
  return (
    <div className="min-h-screen flex flex-col bg-[#f8f9fa]">
      <Header />
      <Outlet />
      <footer className="text-center py-6 text-sm text-gray-500">
        <p>Generated by EverettYoung LLC Value Curve App</p>
      </footer>
    </div>
  );
}

export default App;
